name: Tests

on:
  push:
    branches:
      - master
      - develop

  workflow_dispatch: ~

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install ZUnit
        run: |
          curl -L https://github.com/zunit-zsh/zunit/releases/download/v0.8.2/zunit > /usr/local/bin/zunit
          curl -L https://raw.githubusercontent.com/molovo/revolver/master/revolver > /usr/local/bin/revolver
          curl -L https://raw.githubusercontent.com/molovo/color/master/color.zsh > /usr/local/bin/color
          chmod +x /usr/local/bin/{color,revolver,zunit}
          chmod +x tests/_support/bin/*

      - name: Run tests
        run: zunit
